//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("GolfSwedenModel", "FK_Clubs_Districts", "Districts", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Golfaisverige.Data.Districts), "Clubs", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Golfaisverige.Data.Clubs), true)]
[assembly: EdmRelationshipAttribute("GolfSwedenModel", "FK_Courses_Clubs", "Clubs", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Golfaisverige.Data.Clubs), "Courses", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Golfaisverige.Data.Courses), true)]

#endregion

namespace Golfaisverige.Data
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class GolfSwedenEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new GolfSwedenEntities object using the connection string found in the 'GolfSwedenEntities' section of the application configuration file.
        /// </summary>
        public GolfSwedenEntities() : base("name=GolfSwedenEntities", "GolfSwedenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GolfSwedenEntities object.
        /// </summary>
        public GolfSwedenEntities(string connectionString) : base(connectionString, "GolfSwedenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new GolfSwedenEntities object.
        /// </summary>
        public GolfSwedenEntities(EntityConnection connection) : base(connection, "GolfSwedenEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Clubs> Clubs
        {
            get
            {
                if ((_Clubs == null))
                {
                    _Clubs = base.CreateObjectSet<Clubs>("Clubs");
                }
                return _Clubs;
            }
        }
        private ObjectSet<Clubs> _Clubs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Courses> Courses
        {
            get
            {
                if ((_Courses == null))
                {
                    _Courses = base.CreateObjectSet<Courses>("Courses");
                }
                return _Courses;
            }
        }
        private ObjectSet<Courses> _Courses;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Districts> Districts
        {
            get
            {
                if ((_Districts == null))
                {
                    _Districts = base.CreateObjectSet<Districts>("Districts");
                }
                return _Districts;
            }
        }
        private ObjectSet<Districts> _Districts;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Clubs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClubs(Clubs clubs)
        {
            base.AddObject("Clubs", clubs);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Courses EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCourses(Courses courses)
        {
            base.AddObject("Courses", courses);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Districts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDistricts(Districts districts)
        {
            base.AddObject("Districts", districts);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GolfSwedenModel", Name="Clubs")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Clubs : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Clubs object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        public static Clubs CreateClubs(global::System.Int32 id, global::System.String name)
        {
            Clubs clubs = new Clubs();
            clubs.Id = id;
            clubs.Name = name;
            return clubs;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MapLat
        {
            get
            {
                return _MapLat;
            }
            set
            {
                OnMapLatChanging(value);
                ReportPropertyChanging("MapLat");
                _MapLat = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MapLat");
                OnMapLatChanged();
            }
        }
        private global::System.String _MapLat;
        partial void OnMapLatChanging(global::System.String value);
        partial void OnMapLatChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MapLng
        {
            get
            {
                return _MapLng;
            }
            set
            {
                OnMapLngChanging(value);
                ReportPropertyChanging("MapLng");
                _MapLng = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MapLng");
                OnMapLngChanged();
            }
        }
        private global::System.String _MapLng;
        partial void OnMapLngChanging(global::System.String value);
        partial void OnMapLngChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Drivingrange
        {
            get
            {
                return _Drivingrange;
            }
            set
            {
                OnDrivingrangeChanging(value);
                ReportPropertyChanging("Drivingrange");
                _Drivingrange = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Drivingrange");
                OnDrivingrangeChanged();
            }
        }
        private Nullable<global::System.Boolean> _Drivingrange;
        partial void OnDrivingrangeChanging(Nullable<global::System.Boolean> value);
        partial void OnDrivingrangeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Homepage
        {
            get
            {
                return _Homepage;
            }
            set
            {
                OnHomepageChanging(value);
                ReportPropertyChanging("Homepage");
                _Homepage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Homepage");
                OnHomepageChanged();
            }
        }
        private global::System.String _Homepage;
        partial void OnHomepageChanging(global::System.String value);
        partial void OnHomepageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Pay_n_play
        {
            get
            {
                return _Pay_n_play;
            }
            set
            {
                OnPay_n_playChanging(value);
                ReportPropertyChanging("Pay_n_play");
                _Pay_n_play = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Pay_n_play");
                OnPay_n_playChanged();
            }
        }
        private Nullable<global::System.Boolean> _Pay_n_play;
        partial void OnPay_n_playChanging(Nullable<global::System.Boolean> value);
        partial void OnPay_n_playChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Restaurant
        {
            get
            {
                return _Restaurant;
            }
            set
            {
                OnRestaurantChanging(value);
                ReportPropertyChanging("Restaurant");
                _Restaurant = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Restaurant");
                OnRestaurantChanged();
            }
        }
        private Nullable<global::System.Boolean> _Restaurant;
        partial void OnRestaurantChanging(Nullable<global::System.Boolean> value);
        partial void OnRestaurantChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DistrictId
        {
            get
            {
                return _DistrictId;
            }
            set
            {
                OnDistrictIdChanging(value);
                ReportPropertyChanging("DistrictId");
                _DistrictId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DistrictId");
                OnDistrictIdChanged();
            }
        }
        private Nullable<global::System.Int32> _DistrictId;
        partial void OnDistrictIdChanging(Nullable<global::System.Int32> value);
        partial void OnDistrictIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GolfSwedenModel", "FK_Clubs_Districts", "Districts")]
        public Districts Districts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Districts>("GolfSwedenModel.FK_Clubs_Districts", "Districts").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Districts>("GolfSwedenModel.FK_Clubs_Districts", "Districts").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Districts> DistrictsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Districts>("GolfSwedenModel.FK_Clubs_Districts", "Districts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Districts>("GolfSwedenModel.FK_Clubs_Districts", "Districts", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GolfSwedenModel", "FK_Courses_Clubs", "Courses")]
        public EntityCollection<Courses> Courses
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Courses>("GolfSwedenModel.FK_Courses_Clubs", "Courses");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Courses>("GolfSwedenModel.FK_Courses_Clubs", "Courses", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GolfSwedenModel", Name="Courses")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Courses : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Courses object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="club_id">Initial value of the Club_id property.</param>
        public static Courses CreateCourses(global::System.Int32 id, global::System.Int32 club_id)
        {
            Courses courses = new Courses();
            courses.Id = id;
            courses.Club_id = club_id;
            return courses;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Club_id
        {
            get
            {
                return _Club_id;
            }
            set
            {
                OnClub_idChanging(value);
                ReportPropertyChanging("Club_id");
                _Club_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Club_id");
                OnClub_idChanged();
            }
        }
        private global::System.Int32 _Club_id;
        partial void OnClub_idChanging(global::System.Int32 value);
        partial void OnClub_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Number_of_holes
        {
            get
            {
                return _Number_of_holes;
            }
            set
            {
                OnNumber_of_holesChanging(value);
                ReportPropertyChanging("Number_of_holes");
                _Number_of_holes = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number_of_holes");
                OnNumber_of_holesChanged();
            }
        }
        private Nullable<global::System.Int32> _Number_of_holes;
        partial void OnNumber_of_holesChanging(Nullable<global::System.Int32> value);
        partial void OnNumber_of_holesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Par
        {
            get
            {
                return _Par;
            }
            set
            {
                OnParChanging(value);
                ReportPropertyChanging("Par");
                _Par = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Par");
                OnParChanged();
            }
        }
        private Nullable<global::System.Int32> _Par;
        partial void OnParChanging(Nullable<global::System.Int32> value);
        partial void OnParChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GolfSwedenModel", "FK_Courses_Clubs", "Clubs")]
        public Clubs Clubs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clubs>("GolfSwedenModel.FK_Courses_Clubs", "Clubs").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clubs>("GolfSwedenModel.FK_Courses_Clubs", "Clubs").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Clubs> ClubsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Clubs>("GolfSwedenModel.FK_Courses_Clubs", "Clubs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Clubs>("GolfSwedenModel.FK_Courses_Clubs", "Clubs", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GolfSwedenModel", Name="Districts")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Districts : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Districts object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="externalId">Initial value of the ExternalId property.</param>
        public static Districts CreateDistricts(global::System.Int32 id, global::System.String name, global::System.Guid externalId)
        {
            Districts districts = new Districts();
            districts.Id = id;
            districts.Name = name;
            districts.ExternalId = externalId;
            return districts;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ExternalId
        {
            get
            {
                return _ExternalId;
            }
            set
            {
                OnExternalIdChanging(value);
                ReportPropertyChanging("ExternalId");
                _ExternalId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExternalId");
                OnExternalIdChanged();
            }
        }
        private global::System.Guid _ExternalId;
        partial void OnExternalIdChanging(global::System.Guid value);
        partial void OnExternalIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("GolfSwedenModel", "FK_Clubs_Districts", "Clubs")]
        public EntityCollection<Clubs> Clubs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Clubs>("GolfSwedenModel.FK_Clubs_Districts", "Clubs");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Clubs>("GolfSwedenModel.FK_Clubs_Districts", "Clubs", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
